name: ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  mac-os:
    runs-on: macos-15
    strategy:
      matrix:
        xcode: ["16.0"]
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}
      - uses: actions/checkout@v4
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
#   linux:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         swift: [ "5.7" ]
#     container:
#       image: swift:${{ matrix.swift }}
#     steps:
#       - uses: actions/checkout@v3
#       - name: Build
#         run: swift build
#       - name: Run tests
#         run: swift test
